"""empty message

Revision ID: 06462bb3b7a0
Revises: cf0a04ce4c23
Create Date: 2024-08-01 20:48:44.323899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06462bb3b7a0'
down_revision = 'cf0a04ce4c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grocery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grocery')
    # ### end Alembic commands ###
