"""User model email_id added with uniqueness

Revision ID: 11553b8d97a6
Revises: 9a59329f1b6d
Create Date: 2024-08-02 15:15:50.888116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11553b8d97a6'
down_revision = '9a59329f1b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_id', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['email_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email_id')

    # ### end Alembic commands ###
