"""update grocery_name

Revision ID: 1a732bf693cd
Revises: f4344c556cde
Create Date: 2024-08-05 20:27:19.481457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a732bf693cd'
down_revision = 'f4344c556cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grocery_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('product_type', sa.String(length=80), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grocery_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_grocery_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grocery_name_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grocery_name_id'], ['grocery_name.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('product')
    with op.batch_alter_table('grocery_type', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('grocery_type')
    op.drop_table('user_grocery_type')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('address')
        batch_op.create_unique_constraint(None, ['email_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('address', ['address'], unique=True)

    op.create_table('user_grocery_type',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('grocery_type_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['grocery_type_id'], ['grocery_type.id'], name='user_grocery_type_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_grocery_type_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('grocery_type',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('grocery_type', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    op.create_table('product',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('product_type', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('expiry_date', sa.DATE(), nullable=False),
    sa.Column('grocery_type_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('store_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['grocery_type_id'], ['grocery_type.id'], name='product_ibfk_1'),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], name='product_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_grocery_name')
    op.drop_table('grocery_name')
    op.drop_table('grocery_item')
    # ### end Alembic commands ###
