"""update models and add indexes on keys

Revision ID: a944615871d4
Revises: 9cb357f75f7c
Create Date: 2024-08-25 17:24:17.893307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a944615871d4'
down_revision = '9cb357f75f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery_item', schema=None) as batch_op:
        batch_op.create_index('ix_grocery_item', ['grocery_name_id', 'item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grocery_item_grocery_name_id'), ['grocery_name_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grocery_item_item_id'), ['item_id'], unique=False)

    with op.batch_alter_table('grocery_name', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grocery_name_grocery_type'), ['grocery_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_grocery_name_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_grocery_name_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_type', sa.String(length=80), nullable=False))
        batch_op.drop_index('name')
        batch_op.create_index(batch_op.f('ix_product_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_product_type'), ['product_type'], unique=False)
        batch_op.drop_column('type')

    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_index('name')
        batch_op.create_index(batch_op.f('ix_store_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_name'), ['name'], unique=True)

    with op.batch_alter_table('store_product_mapping', schema=None) as batch_op:
        batch_op.create_index('ix_store_product', ['store_id', 'product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_product_mapping_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_product_mapping_store_id'), ['store_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('username')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index('username', ['username'], unique=True)

    with op.batch_alter_table('store_product_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_product_mapping_store_id'))
        batch_op.drop_index(batch_op.f('ix_store_product_mapping_product_id'))
        batch_op.drop_index('ix_store_product')

    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_name'))
        batch_op.drop_index(batch_op.f('ix_store_location'))
        batch_op.create_index('name', ['name'], unique=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=80), nullable=False))
        batch_op.drop_index(batch_op.f('ix_product_product_type'))
        batch_op.drop_index(batch_op.f('ix_product_name'))
        batch_op.create_index('name', ['name'], unique=True)
        batch_op.drop_column('product_type')

    with op.batch_alter_table('grocery_name', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grocery_name_user_id'))
        batch_op.drop_index(batch_op.f('ix_grocery_name_name'))
        batch_op.drop_index(batch_op.f('ix_grocery_name_grocery_type'))

    with op.batch_alter_table('grocery_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grocery_item_item_id'))
        batch_op.drop_index(batch_op.f('ix_grocery_item_grocery_name_id'))
        batch_op.drop_index('ix_grocery_item')

    # ### end Alembic commands ###
